/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticket;

import org.ticket.service.userBookingService;

import java.io.IOException;
import java.util.List;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {



        System.out.println("Running train Booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        userBookingService userBookingService;
        try
        {
            userBookingService=new userBookingService();
        }
        catch (IOException e)
        {
            System.out.println("there is something wrong");
            return;
        }
        while (option!=7)
        {
            System.out.println("choose options");
            System.out.println("1.sign up");
            System.out.println("2.login");
            System.out.println("3. fetch Booking");
            System.out.println("4. search trains");
            System.out.println("Book a seats");
            System.out.println("6. cancel my booking");
            System.out.println("7. exit");

            option= sc.nextInt();
            switch (option)
            {
                case 1:
            }
        }
    }
}
